/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demohinhchunhat_gui;

/**
 *
 * @author Levisa
 */
public class HinhChuNhatGUI extends javax.swing.JFrame {

    /**
     * Creates new form HinhChuNhatGUI
     */
    public HinhChuNhatGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ketQuaLabel = new javax.swing.JLabel();
        tinhChuViButton = new javax.swing.JButton();
        tinhDienTichButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chieuDaiTextField = new javax.swing.JTextField();
        chieuRongTextField = new javax.swing.JTextField();
        ketQuaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chiều dài");

        jLabel2.setText("Chiều rộng");

        ketQuaLabel.setText("jLabel3");

        tinhChuViButton.setText("Tính chu vi");
        tinhChuViButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhChuViButtonActionPerformed(evt);
            }
        });

        tinhDienTichButton.setText("Tính diện tích");
        tinhDienTichButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhDienTichButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 255));
        jLabel4.setText("TÍNH DIỆN TÍCH VÀ CHU VI HÌNH CHỮ NHẬT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tinhChuViButton)
                        .addGap(58, 58, 58)
                        .addComponent(tinhDienTichButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(ketQuaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chieuRongTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(chieuDaiTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ketQuaTextField))
                        .addContainerGap(228, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chieuDaiTextField, chieuRongTextField, ketQuaTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chieuDaiTextField))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chieuRongTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ketQuaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketQuaTextField))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinhDienTichButton)
                    .addComponent(tinhChuViButton))
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tinhChuViButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhChuViButtonActionPerformed
        float chieuDai = Float.parseFloat(chieuDaiTextField.getText());
        float chieuRong = Float.parseFloat(chieuRongTextField.getText());
        HinhChuNhat hcn = new HinhChuNhat(chieuDai, chieuRong);
        float chuVi = hcn.tinhChuVi();
        ketQuaLabel.setText("Chu vi là:");
        ketQuaTextField.setText(chuVi + "");
    }//GEN-LAST:event_tinhChuViButtonActionPerformed

    private void tinhDienTichButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhDienTichButtonActionPerformed
        float chieuDai = Float.parseFloat(chieuDaiTextField.getText());
        float chieuRong = Float.parseFloat(chieuRongTextField.getText());
        HinhChuNhat hcn = new HinhChuNhat(chieuDai, chieuRong);
        float dienTich = hcn.tinhDienTich();
        ketQuaLabel.setText("Diện tích là:");
        ketQuaTextField.setText(dienTich + "");
    }//GEN-LAST:event_tinhDienTichButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HinhChuNhatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HinhChuNhatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HinhChuNhatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HinhChuNhatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HinhChuNhatGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chieuDaiTextField;
    private javax.swing.JTextField chieuRongTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ketQuaLabel;
    private javax.swing.JTextField ketQuaTextField;
    private javax.swing.JButton tinhChuViButton;
    private javax.swing.JButton tinhDienTichButton;
    // End of variables declaration//GEN-END:variables
}
