/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demongaytruocngaysau;

/**
 *
 * @author SV
 */
public class NgayTruocNgaySau_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NgayTruocNgaySau_GUI
     */
    public NgayTruocNgaySau_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ngayTextField = new javax.swing.JTextField();
        thangTextField = new javax.swing.JTextField();
        namTextField = new javax.swing.JTextField();
        ngayTruocButton = new javax.swing.JButton();
        ngaySauButton = new javax.swing.JButton();
        ketQuaLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ketQuaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ngày");

        jLabel2.setText("Tháng");

        jLabel3.setText("Năm");

        ngayTruocButton.setText("Ngày trước");
        ngayTruocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayTruocButtonActionPerformed(evt);
            }
        });

        ngaySauButton.setText("Ngày sau");
        ngaySauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySauButtonActionPerformed(evt);
            }
        });

        ketQuaLabel.setText("Kết quả");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ngayTruocButton)
                        .addGap(33, 33, 33)
                        .addComponent(ngaySauButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ketQuaLabel))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ngayTextField)
                            .addComponent(thangTextField)
                            .addComponent(namTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(ketQuaTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ngayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(thangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ketQuaLabel)
                            .addComponent(ketQuaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayTruocButton)
                    .addComponent(ngaySauButton))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ngayTruocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayTruocButtonActionPerformed
        // TODO add your handling code here:
        int ngay = Integer.parseInt(ngayTextField.getText());
        int thang = Integer.parseInt(thangTextField.getText());
        int nam = Integer.parseInt(namTextField.getText());
        NgayThangNam ngayThangNam = new NgayThangNam(ngay,thang,nam);
        NgayThangNam ngayTruoc = new NgayThangNam();
        ngayTruoc = ngayThangNam.ngayTruoc();
        ketQuaTextField.setText(ngayTruoc.getNgay() + " - " + ngayTruoc.getThang() + " - " + ngayTruoc.getNam());
    }//GEN-LAST:event_ngayTruocButtonActionPerformed

    private void ngaySauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySauButtonActionPerformed
        // TODO add your handling code here:
                int ngay = Integer.parseInt(ngayTextField.getText());
        int thang = Integer.parseInt(thangTextField.getText());
        int nam = Integer.parseInt(namTextField.getText());
        NgayThangNam ngayThangNam = new NgayThangNam(ngay,thang,nam);
        ngayThangNam = ngayThangNam.ngaySau();
        ketQuaTextField.setText(ngayThangNam.getNgay() + " - " + ngayThangNam.getThang() + " - " + ngayThangNam.getNam());
    }//GEN-LAST:event_ngaySauButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NgayTruocNgaySau_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NgayTruocNgaySau_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NgayTruocNgaySau_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NgayTruocNgaySau_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NgayTruocNgaySau_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel ketQuaLabel;
    private javax.swing.JTextField ketQuaTextField;
    private javax.swing.JTextField namTextField;
    private javax.swing.JButton ngaySauButton;
    private javax.swing.JTextField ngayTextField;
    private javax.swing.JButton ngayTruocButton;
    private javax.swing.JTextField thangTextField;
    // End of variables declaration//GEN-END:variables
}
